// The content in this file is autogenerated by eslint - run `pnpm lint:codegen` to update it.
// See https://npmjs.com/package/eslint-plugin-codegen for more details.

// codegen:start {preset: barrel, include: './*.ts', import: default, extension: {ts: 'js'}, export: {name: migrations, keys: path}}
import _20240627T175800Init from "./2024-06-27T17-58-00-init.js";
import _20240627T175900Cleanup from "./2024-06-27T17-59-00-cleanup.js";
import _20240627T190700AddRequestId from "./2024-06-27T19-07-00-add-request-id.js";

export const migrations = {
  "./2024-06-27T17-58-00-init.js": _20240627T175800Init,
  "./2024-06-27T17-59-00-cleanup.js": _20240627T175900Cleanup,
  "./2024-06-27T19-07-00-add-request-id.js": _20240627T190700AddRequestId
};
// codegen:end
